# Generated by Django 5.0.3 on 2024-03-12 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwordmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordsmanagermodel',
            name='name',
            field=models.CharField(default='ok', max_length=10),
            preserve_default=False,
        ),
    ]
