# Generated by Django 5.0.3 on 2024-03-12 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwordmanager', '0002_passwordsmanagermodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordsmanagermodel',
            name='username',
            field=models.TextField(default='ok'),
            preserve_default=False,
        ),
    ]
