# Generated by Django 5.0.3 on 2024-03-12 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwordmanager', '0004_alter_passwordsmanagermodel_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordsmanagermodel',
            name='username',
            field=models.BinaryField(),
        ),
    ]
